# Generated by Django 5.2.16 on 2026-08-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_popup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='popup_seen',
            field=models.BooleanField(default=False),
        ),
    ]
