# Generated by Django 5.2.16 on 2026-08-04 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.assignment')),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_visit', to='attendance.attendance')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.client')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.worktype')),
            ],
        ),
    ]
