# Generated by Django 5.2.16 on 2026-08-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Policy', max_length=100)),
                ('deduct_unapproved_leave', models.BooleanField(default=True, help_text='Deduct 1 day salary for unapproved absences')),
                ('sandwich_rule_active', models.BooleanField(default=True, help_text='Deduct holiday salary if absent adjacent to holiday')),
                ('late_deduction_active', models.BooleanField(default=True)),
                ('first_lates_for_penalty', models.IntegerField(default=3, help_text='Number of initial late days that equal 1 absent day')),
                ('subsequent_lates_for_penalty', models.IntegerField(default=2, help_text='Number of subsequent late days that equal 1 absent day')),
            ],
            options={
                'verbose_name_plural': 'Payroll Policies',
            },
        ),
    ]
