# Generated by Django 5.2.16 on 2026-08-13 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrollpolicy'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPayrollLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('per_day_salary', models.DecimalField(decimal_places=2, default=0, help_text='Base stipend / 30', max_digits=10)),
                ('daily_conveyance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('attendance_status', models.CharField(default='N/A', help_text='Present/Late/Absent/Leave/Holiday/Weekend', max_length=20)),
                ('is_working_day', models.BooleanField(default=True)),
                ('late_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('leave_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sandwich_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('daily_net', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_payroll_logs', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Daily Payroll Log',
                'verbose_name_plural': 'Daily Payroll Logs',
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
