# Generated by Django 5.2.16 on 2026-08-07 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conveyance', '0001_initial'),
        ('practice', '0002_clientvisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conveyance',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='conveyance',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='conveyance',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='conveyance',
            name='client',
        ),
        migrations.RemoveField(
            model_name='conveyance',
            name='description',
        ),
        migrations.RemoveField(
            model_name='conveyance',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='conveyance',
            name='to_location',
        ),
        migrations.RemoveField(
            model_name='conveyance',
            name='transport',
        ),
        migrations.AddField(
            model_name='conveyance',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='ConveyanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('transport', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='conveyance_bills/')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='practice.assignment')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='practice.client')),
                ('conveyance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='conveyance.conveyance')),
            ],
        ),
    ]
